### ISSUE TITLE
Rename + Feature Request

### ISSUE THREAD

**Issue by xItzDiamondx** [TheColaber/reflect#1]
I can't rename a file name. Also, turn this into a text editor that supports HTML and CSS and other languages?

**Comment by TheColaber** [comment]
> I can't rename a file name.

Why can't you rename a file? I am able to... Can you provide steps or record yourself?

> Also, turn this into a text editor that supports HTML and CSS and other languages?

I kinda wanted this to just be a simple notepad with tiny features. Not into anything too complicated because
1. There will be no way to run it
2. There will be no reason to store it in this notepad.

**Comment by xItzDiamondx** [comment]
Sure. I'll record
