### ISSUE TITLE
feature request - markdown support

### ISSUE THREAD

**Issue by ghost** [TheColaber/reflect#5]
it would be very useful

cc @TheColaber

**Comment by TheColaber** [comment]
Rejected, I have other plans...

**Comment by ghost** [comment]
> Rejected, I have other plans...

@TheColaber like what

**Comment by TheColaber** [comment]
What's going on currently... A wysiwyg editor

**Comment by ghost** [comment]
> What's going on currently... A wysiwyg editor

@TheColaber why can't you have markdown alongside it

**Comment by TheColaber** [comment]
Bc they don't mix

**Comment by ghost** [comment]
> Bc they don't mix

@TheColaber idk about that

**Comment by TheColaber** [comment]
How do you mix
```
Test
```
With
\`\`\`
Test
\`\`\`
